apiVersion: v1
kind: Service
metadata:
  name: my-nginx-clusterip
  namespace: comp-app-namespace

spec:
  type: ClusterIP
  
  selector:
    app: comp-app
    component: frontend
  
  ports:
    - port: 80
      targetPort: 80
  