apiVersion: v1
kind: Service
metadata:
  name: my-nginx-node-port
  namespace: comp-app-namespace

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31003

  selector:
    app: comp-app
    component: frontend
