apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: comp-app
    component: web

spec:
  replicas: 1

  selector: 
    matchLabels:
      app: comp-app
      component: web

  template:
    metadata:
      name: nginx-pod
      labels:
        app: comp-app
        component: web
    spec:
      containers:
        - name: nginx-container
          image: marekprezes/comp-app_frontend:latest
