apiVersion: v1
kind: Service
metadata:
  name: mybackend-node-port

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
  
  selector:
    app: my-app
    component: backend