apiVersion: v1
kind: Service
metadata:
  name: mypostgres-node-port

spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31001
  
  selector:
    app: my-app
    component: db