apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-deployment
  namespace: comp-app-namespace
  labels:
    app: comp-app
    component: cache

spec:
  replicas: 1

  selector: 
    matchLabels:
      app: comp-app
      component: cache
  
  template:
    metadata:
      name: my-redis-pod
      labels:
        app: comp-app
        component: cache
    spec:
      containers:
        - name: my-redis-container
          image: redis:alpine
          ports:
            - containerPort: 6379

