apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: comp-app
    component: cache

spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
      - containerPort: 6379
