apiVersion: v1
kind: Service
metadata:
  name: my-postgres-clusterip
  namespace: comp-app-namespace

spec:
  type: ClusterIP

  selector:
    app: comp-app
    component: db
  
  ports:
    - port: 5432
      targetPort: 5432
