apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc

spec:
  storageClassName: manual # po tym będzie dopasowanie
  accessModes:
    - ReadWriteOnce # jednocześnie dostęp tylko z jednego noda
  resources:
    requests:
      storage: 10Mi
