apiVersion: v1
kind: Service
metadata:
  name: my-backend-node-port
  namespace: comp-app-namespace

spec:
  type: NodePort
  
  selector:
    app: comp-app
    component: backend
  
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
