apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  namespace: comp-app-namespace
  labels:
    app: comp-app
    component: backend

spec:
  replicas: 3

  selector: 
    matchLabels:
      app: comp-app
      component: backend
  
  template:
    metadata:
      name: my-backend-pod
      labels:
        app: comp-app
        component: backend
    spec:
      containers:
        - name: my-backend-container
          image: marekprezes/comp-app_backend:latest
          env:
            # mapowanie ENV z ConfigMap dla postgres
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: PG_HOST
              
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: PG_PORT
              
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: PG_DB
            
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: PG_USER
            
            # mapowanie EVN z secret
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: my-postgres-secret
                  key: PG_PASS
            
            # mapowanie ENV z ConfigMap dla redisa
            - name: RD_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-redis-config
                  key: RD_HOST
            
            - name: RD_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-redis-config
                  key: RD_PORT
